remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: Ã‰tienne Dyer
logo: assets/logo.jpg
favicon: true
color-scheme: light
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

platforms:
  - name: Home
    link: https://etiennedyer.github.io/
    icon: <i class="fa-solid fa-house"></i>
    
  - name: Art
    link: https://etiennedyer.github.io/pages/art
    icon: <i class="fa-solid fa-eye"></i>

  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/etiennedyer
    
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/%C3%A9tienne-dyer-39a2682a7/



